openapi: 3.0.3
info:
  title: Acme Bank
  description: Acme Bank documentation for creating and managing bank accounts
  version: 1.0.0
servers:
  - url: https://localhost:3000/api/v1
tags:
  - name: bank_account
    description: Bank account operations
  - name: account_holder
    description: Account holder operations
paths:
  /health_check:
    get:
      summary: Health check endpoint
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum:
                      - ok
                    example: ok
  /bank_accounts:
    get:
      tags:
        - bank_account
      summary: List bank accounts
      operationId: bankAccountIndex
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 11
                    type:
                      type: string
                      enum:
                        - CURRENT
                        - SAVINGS
                      example: CURRENT
                    status:
                      type: string
                      enum:
                        - OPEN
                        - CLOSED
                      example: OPEN
                    account_holder:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 22
                        name:
                          type: string
                          example: John Doe
                        age:
                          type: integer
                          example: 87
    post:
      tags:
        - bank_account
      summary: Create new bank account
      operationId: bankAccountCreate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                account_holder_id:
                  type: integer
                  example: 22
                type:
                  type: string
                  enum:
                    - CURRENT
                    - SAVINGS
                  example: CURRENT
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 11
                  type:
                    type: string
                    enum:
                      - CURRENT
                      - SAVINGS
                    example: CURRENT
                  status:
                    type: string
                    enum:
                      - OPEN
                      - CLOSED
                    example: OPEN
                  account_holder_id:
                    type: integer
                    example: 22
        "422":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Account holder already has an account of this type
                        field:
                          type: string
                          example: account_holder_id
  /bank_accounts/{id}:
    get:
      tags:
        - bank_account
      summary: Show bank account details
      operationId: bankAccountShow
      parameters:
        - name: id
          in: path
          description: Bank account Identifier
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 11
                  type:
                    type: string
                    enum:
                      - CURRENT
                      - SAVINGS
                    example: CURRENT
                  status:
                    type: string
                    enum:
                      - OPEN
                      - CLOSED
                    example: OPEN
                  account_holder_id:
                    type: integer
                    example: 22
        "404":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Bank account could not be found
                        field:
                          type: string
                          example: account_holder_id
    delete:
      tags:
        - bank_account
      summary: Close bank account
      operationId: bankAccountDelete
      parameters:
        - name: id
          in: path
          description: Bank account Identifier
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 11
                  type:
                    type: string
                    enum:
                      - CURRENT
                      - SAVINGS
                    example: CURRENT
                  status:
                    type: string
                    enum:
                      - CLOSED
                    example: CLOSED
                  account_holder_id:
                    type: integer
                    example: 22
        "404":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Bank account could not be found
                        field:
                          type: string
                          example: account_holder_id
        "422":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Bank account is already closed
                        field:
                          type: string
                          example: account_holder_id

  /account_holders:
    get:
      tags:
        - account_holder
      summary: List account holders
      operationId: accountHolderIndex
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 22
                    name:
                      type: string
                      example: John Doe
                    age:
                      type: integer
                      example: 87
    post:
      tags:
        - account_holder
      summary: Create new account holder
      operationId: accountHolderCreate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                age:
                  type: integer
                  example: 87
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 22
                  name:
                    type: string
                    example: John Doe
                  age:
                    type: integer
                    example: 87
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: field name cannot be blank
                        field:
                          type: string
                          example: name
  /account_holders/{id}:
    get:
      tags:
        - account_holder
      summary: Show account holder details
      operationId: accountHolderShow
      parameters:
        - name: id
          in: path
          description: Account holder identifier
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 22
                  name:
                    type: string
                    example: John Doe
                  age:
                    type: integer
                    example: 87
        "404":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Account holder could not be found
                        field:
                          type: string
                          example: account_holder_id
