openapi: 3.0.3
info:
  title: Acme Bank
  description: Acme Bank documentation for creating and managing bank accounts
  version: 1.0.0
servers:
  - url: https://localhost:3000/api/v1
tags:
  - name: account
    description: Account operations
  - name: holder
    description: Account holder operations
paths:
  /accounts:
    get:
      tags:
        - account
      summary: List accounts
      operationId: accountIndex
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 11
                    type:
                      type: string
                      enum:
                        - normal
                        - savings
                      example: normal
                    status:
                      type: string
                      enum:
                        - open
                        - closed
                      example: open
                    holder:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 22
                        name: 
                          type: string
                          example: John Doe
                        age:
                          type: integer
                          example: 87
    post:
      tags:
        - account
      summary: Create new bank account
      operationId: accountCreate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                holder_id:
                  type: integer
                  example: 22
                type:
                  type: string
                  enum:
                    - normal
                    - savings
                  example: normal
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 11
                  type:
                    type: string
                    enum:
                      - normal
                      - savings
                    example: normal
                  status:
                    type: string
                    enum:
                      - open
                      - closed
                    example: open
                  holder_id:
                    type: integer
                    example: 22
        '422':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Account holder already has an account of this type
        '404':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Account holder could not be found
  /accounts/{id}:
    get:
      tags:
        - account
      summary: Show account details
      operationId: accountShow
      parameters:
        - name: id
          in: path
          description: Account Identifier
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 11
                  type:
                    type: string
                    enum:
                      - normal
                      - savings
                    example: normal
                  status:
                    type: string
                    enum:
                      - open
                      - closed
                    example: open
                  holder_id:
                    type: integer
                    example: 22
        '404':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Account could not be found
    delete:
      tags:
        - account
      summary: Close account
      operationId: accountDelete
      parameters:
        - name: id
          in: path
          description: Account Identifier
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 11
                  type:
                    type: string
                    enum:
                      - normal
                      - savings
                    example: normal
                  status:
                    type: string
                    enum:
                      - closed
                    example: closed
                  holder_id:
                    type: integer
                    example: 22
        '404':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Account could not be found
        '422':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Account is already closed
  /holders:
    get:
      tags:
        - holder
      summary: List holders
      operationId: holderIndex
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 22
                    name: 
                      type: string
                      example: John Doe
                    age:
                      type: integer
                      example: 87
    post:
      tags:
        - holder
      summary: Create new account holder
      operationId: holderCreate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                age:
                  type: integer
                  example: 87
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 22
                  name:
                    type: string
                    example: John Doe
                  age:
                    type: integer
                    example: 87
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: field name cannot be blank
  /holders/{id}:
    get:
      tags:
        - holder
      summary: Show holder account details
      operationId: holderShow
      parameters:
        - name: id
          in: path
          description: Account holder identifier
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 22
                  name:
                    type: string
                    example: John Doe
                  age:
                    type: integer
                    example: 87
        '404':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Account holder could not be found