openapi: 3.0.3
info:
  title: Acme Bank
  description: Acme Bank documentation for creating and managing bank accounts
  version: 1.0.0
servers:
  - url: https://localhost:3000/api/v1
tags:
  - name: bank_account
    description: Bank account operations
  - name: account_holder
    description: Account holder operations
paths:
  /bank_accounts:
    get:
      tags:
        - bank_account
      summary: List bank accounts
      operationId: bankAccountIndex
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 11
                    type:
                      type: string
                      enum:
                        - current
                        - savings
                      example: current
                    status:
                      type: string
                      enum:
                        - open
                        - closed
                      example: open
                    account_holder:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 22
                        name:
                          type: string
                          example: John Doe
                        age:
                          type: integer
                          example: 87
    post:
      tags:
        - bank_account
      summary: Create new bank account
      operationId: bankAccountCreate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                account_holder_id:
                  type: integer
                  example: 22
                type:
                  type: string
                  enum:
                    - current
                    - savings
                  example: current
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 11
                  type:
                    type: string
                    enum:
                      - current
                      - savings
                    example: current
                  status:
                    type: string
                    enum:
                      - open
                      - closed
                    example: open
                  account_holder_id:
                    type: integer
                    example: 22
        "422":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Account holder already has an account of this type
        "404":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Account holder could not be found
  /bank_accounts/{id}:
    get:
      tags:
        - bank_account
      summary: Show bank account details
      operationId: bankAccountShow
      parameters:
        - name: id
          in: path
          description: Bank account Identifier
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 11
                  type:
                    type: string
                    enum:
                      - current
                      - savings
                    example: current
                  status:
                    type: string
                    enum:
                      - open
                      - closed
                    example: open
                  account_holder_id:
                    type: integer
                    example: 22
        "404":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Bank account could not be found
    delete:
      tags:
        - bank_account
      summary: Close bank account
      operationId: bankAccountDelete
      parameters:
        - name: id
          in: path
          description: Bank account Identifier
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 11
                  type:
                    type: string
                    enum:
                      - current
                      - savings
                    example: current
                  status:
                    type: string
                    enum:
                      - closed
                    example: closed
                  account_holder_id:
                    type: integer
                    example: 22
        "404":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Bank account could not be found
        "422":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Bank account is already closed
  /account_holders:
    get:
      tags:
        - account_holder
      summary: List account holders
      operationId: accountHolderIndex
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 22
                    name:
                      type: string
                      example: John Doe
                    age:
                      type: integer
                      example: 87
    post:
      tags:
        - account_holder
      summary: Create new account holder
      operationId: accountHolderCreate
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John Doe
                age:
                  type: integer
                  example: 87
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 22
                  name:
                    type: string
                    example: John Doe
                  age:
                    type: integer
                    example: 87
        "400":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: field name cannot be blank
  /account_holders/{id}:
    get:
      tags:
        - account_holder
      summary: Show account holder details
      operationId: accountHolderShow
      parameters:
        - name: id
          in: path
          description: Account holder identifier
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 22
                  name:
                    type: string
                    example: John Doe
                  age:
                    type: integer
                    example: 87
        "404":
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        message:
                          type: string
                          example: Account holder could not be found
